import { useMemo, useState } from 'react';
import { Check, Copy, ExternalLink, Link2, QrCode } from 'lucide-react';
import { Link } from 'wouter';

import { usePartnerPrototype } from './PartnerPrototypeContext';
import {
  PARTNER_MONTHLY_REPORTS, calculatePartnerCommission, createPartnerReportSummary,
  filterPartnerBookings, summarizePartnerCommissions, type PartnerBookingStatus,
} from './partnerPrototypeData';

const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);

export type PartnerSection = 'overview' | 'referral' | 'bookings' | 'commissions' | 'reports' | 'profile';

export default function PartnerDashboardPanels({ activeSection, onSectionChange }: { activeSection: PartnerSection; onSectionChange: (section: PartnerSection) => void }) {
  const context = usePartnerPrototype();
  if (activeSection === 'overview') return <Overview {...context} onSectionChange={onSectionChange}/>;
  if (activeSection === 'referral') return <ReferralTools/>;
  if (activeSection === 'bookings') return <Bookings onSectionChange={onSectionChange}/>;
  if (activeSection === 'commissions') return <Commissions/>;
  if (activeSection === 'reports') return <Reports/>;
  return <PartnerProfile/>;
}

function Header({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <header className="partner-panel-header"><p className="partner-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></header>; }

function Overview({ selectedPartner, referralCampaigns, referredBookings, onSectionChange }: ReturnType<typeof usePartnerPrototype> & { onSectionChange: (section: PartnerSection) => void }) {
  const report = createPartnerReportSummary(referredBookings, referralCampaigns);
  const visits = referralCampaigns.reduce((total, campaign) => total + campaign.visits, 0);
  const available = referredBookings.filter((booking) => booking.commissionStatus === 'available').reduce((total, booking) => total + calculatePartnerCommission(booking), 0);
  const metrics = [['Referral visits — Demo', visits], ['Referred requests', report.referredRequests], ['Confirmed bookings', report.confirmedBookings], ['Completed bookings', report.completedBookings], ['Available commission — Demo', money(available)], ['Conversion rate — Prototype', `${report.conversionRate}%`]];
  return <><Header eyebrow="Partner overview" title={`Welcome, ${selectedPartner.contactDisplayName}`} text="Deterministic referral performance for customer review—not live analytics."/><div className="partner-metrics">{metrics.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="partner-overview-grid"><section className="partner-card"><div className="partner-card-heading"><div><h2>Recent referred bookings</h2><p>Latest guest activity across your demo channels.</p></div><button onClick={()=>onSectionChange('bookings')}>View all</button></div>{referredBookings.slice(0,4).map((booking)=><div className="partner-recent" key={booking.id}><div><strong>{booking.travelerName}</strong><span>{booking.experience} · {booking.guideName}</span></div><div><span className={`partner-status partner-status--${booking.status}`}>{booking.status}</span><time>{booking.date}</time></div></div>)}</section><section className="partner-card"><h2>Quick actions</h2><button className="partner-action-row" onClick={()=>onSectionChange('referral')}><span><Link2 size={17}/><b>Copy referral link</b></span><small>Open Referral Tools</small></button><button className="partner-action-row" onClick={()=>onSectionChange('referral')}><span><QrCode size={17}/><b>View QR prototype</b></span><small>Preview guest-facing asset</small></button><button className="partner-action-row" onClick={()=>onSectionChange('commissions')}><span><Check size={17}/><b>View commissions</b></span><small>See 5% calculation</small></button></section><section className="partner-card partner-card--wide"><h2>Performance summary</h2><div className="partner-campaign-bars">{referralCampaigns.map((campaign)=><div key={campaign.id}><span>{campaign.name}</span><i><b style={{width:`${Math.min(100,campaign.bookings/14*100)}%`}}/></i><strong>{campaign.bookings} bookings</strong></div>)}</div></section></div></>;
}

function DemoQr() { const cells=[0,1,2,5,7,8,10,11,14,16,17,18,20,22,24,25,27,29,30,32,33,35,37,38,40,41,42,44,46,48,49,50,52,54,55,56,58,60,62,64,65,66,68,70,72,73,75,77,78,80]; return <svg className="partner-qr" viewBox="0 0 90 90" role="img" aria-label="Deterministic QR-style prototype graphic"><rect width="90" height="90" fill="white"/>{cells.map((cell)=><rect key={cell} x={(cell%9)*10+2} y={Math.floor(cell/9)*10+2} width="7" height="7" rx="1" fill="#193f32"/>)}<rect x="8" y="8" width="22" height="22" fill="none" stroke="#193f32" strokeWidth="5"/><rect x="60" y="8" width="22" height="22" fill="none" stroke="#193f32" strokeWidth="5"/><rect x="8" y="60" width="22" height="22" fill="none" stroke="#193f32" strokeWidth="5"/></svg>; }

function ReferralTools() { const { generatedDemoLink, referralCampaigns }=usePartnerPrototype(); const [feedback,setFeedback]=useState(''); async function copy(){try{await navigator.clipboard.writeText(`https://${generatedDemoLink}`);setFeedback('Demo referral link copied.');}catch{setFeedback('Clipboard unavailable. Select and copy the demo URL manually.');}} return <><Header eyebrow="Referral tools" title="Share a demo referral experience" text="These assets are visual prototypes and are not connected to tracking or server-side referral records."/><div className="partner-referral-grid"><section className="partner-card"><h2>Referral Link</h2><label className="partner-link-field"><span>Prototype URL</span><input readOnly value={generatedDemoLink}/></label><button className="partner-primary" onClick={copy}><Copy size={16}/>Copy Demo Link</button><p className="partner-live" aria-live="polite">{feedback}</p><Link href="/?ref=saigon-riverside-demo" className="partner-text-link">Preview Guest Landing <ExternalLink size={14}/></Link></section><section className="partner-card partner-qr-card"><DemoQr/><div><h2>QR Prototype</h2><p>Place this deterministic visual on a front-desk card. It does not scan or track real visits.</p><button className="partner-secondary" onClick={copy}>Copy Demo Link</button></div></section></div><section className="partner-section"><h2>Referral campaigns</h2><div className="partner-campaign-grid">{referralCampaigns.map((campaign)=><article key={campaign.id}><span>Demo campaign</span><h3>{campaign.name}</h3><dl><div><dt>Visits</dt><dd>{campaign.visits}</dd></div><div><dt>Requests</dt><dd>{campaign.requests}</dd></div><div><dt>Bookings</dt><dd>{campaign.bookings}</dd></div><div><dt>Conversion</dt><dd>{Math.round(campaign.bookings/campaign.visits*1000)/10}%</dd></div></dl></article>)}</div></section></> }

function Bookings({onSectionChange}:{onSectionChange:(section:PartnerSection)=>void}){
  const {referredBookings}=usePartnerPrototype();
  const [filter,setFilter]=useState<'all'|PartnerBookingStatus>('all');
  const [expandedId,setExpandedId]=useState<string|null>(null);
  const filtered=filterPartnerBookings(referredBookings,filter);

  return <><Header eyebrow="Referred bookings" title="Guest booking activity" text="Partner access is view-only. Contact details and booking modification controls are intentionally omitted."/><div className="partner-filters">{(['all','pending','confirmed','completed','cancelled'] as const).map(item=><button key={item} aria-pressed={filter===item} onClick={()=>setFilter(item)}>{item}</button>)}</div><div className="partner-booking-list">{filtered.map(booking=>{
    const summaryId=`partner-booking-summary-${booking.id}`;
    const expanded=expandedId===booking.id;
    return <article key={booking.id}><header><div><strong>{booking.id}</strong><span>{booking.date}</span></div><span className={`partner-status partner-status--${booking.status}`}>{booking.status}</span></header><dl><div><dt>Traveler</dt><dd>{booking.travelerName}</dd></div><div><dt>Guide</dt><dd>{booking.guideName}</dd></div><div><dt>Experience</dt><dd>{booking.experience}</dd></div><div><dt>Referral source</dt><dd>{booking.referralSource}</dd></div><div><dt>Booking total</dt><dd>{money(booking.total)}</dd></div><div><dt>Commission status</dt><dd>{booking.commissionStatus.replace('-demo',' — Demo')}</dd></div></dl>{expanded&&<p className="partner-booking-summary" id={summaryId}>This demo referral connects {booking.travelerName} with {booking.guideName} for {booking.experience}. Partner access remains read-only.</p>}<footer><button aria-expanded={expanded} aria-controls={summaryId} onClick={()=>setExpandedId(current=>current===booking.id?null:booking.id)}>{expanded?'Hide Booking Summary':'View Booking Summary'}</button><button onClick={()=>onSectionChange('commissions')}>View Commission</button></footer></article>;
  })}</div></>;
}

function Commissions(){const {referredBookings}=usePartnerPrototype();const tx=referredBookings.map(booking=>({id:`COM-${booking.id}`,bookingId:booking.id,amount:calculatePartnerCommission(booking),status:booking.commissionStatus}));const summary=summarizePartnerCommissions(tx);return <><Header eyebrow="Commissions" title="Transparent 5% commission ledger" text="Partner commission = eligible completed booking total × 5%. No payout or bank information is connected."/><div className="partner-metrics partner-metrics--four">{[['Pending commission',money(summary.pending)],['Available commission',money(summary.available)],['Paid — Demo',money(summary.paidDemo)],['Lifetime commission — Demo',money(summary.lifetime)]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="partner-notice">Partner payouts are unavailable in this prototype.</div><div className="partner-commission-list">{referredBookings.map(booking=><article key={booking.id}><div><strong>COM-{booking.id}</strong><span>{booking.id} · {booking.date}</span></div><dl><div><dt>Eligible amount</dt><dd>{booking.status==='completed'?money(booking.total):money(0)}</dd></div><div><dt>Rate</dt><dd>5%</dd></div><div><dt>Commission</dt><dd>{money(calculatePartnerCommission(booking))}</dd></div></dl><span className={`partner-status partner-status--${booking.status}`}>{booking.commissionStatus.replace('-demo',' — Demo')}</span></article>)}</div></>}

function Reports(){const {referredBookings,referralCampaigns}=usePartnerPrototype();const summary=createPartnerReportSummary(referredBookings,referralCampaigns);const max=Math.max(...PARTNER_MONTHLY_REPORTS.map(item=>item.requests));return <><Header eyebrow="Reports" title="Referral performance reports" text="Simple deterministic trends for prototype review—no live analytics or chart service."/><div className="partner-report-summary">{[['Referred requests',summary.referredRequests],['Completed bookings',summary.completedBookings],['Commission earned',money(summary.commissionEarned)],['Best source',summary.bestSource],['Popular experience',summary.popularExperience]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><section className="partner-card"><h2>Requests by month</h2><div className="partner-month-bars">{PARTNER_MONTHLY_REPORTS.map(item=><div key={item.month}><span>{item.month}</span><i><b style={{width:`${item.requests/max*100}%`}}/></i><strong>{item.requests}</strong><small>{item.completed} completed · {money(item.commission)}</small></div>)}</div></section></>}

function PartnerProfile(){const {selectedPartner,updateDemoProfile}=usePartnerPrototype();const [contact,setContact]=useState(selectedPartner.contactDisplayName);const [label,setLabel]=useState(selectedPartner.publicReferralLabel);const [saved,setSaved]=useState(false);return <><Header eyebrow="Partner profile" title="Demo partner details" text="Profile edits stay in local React state and do not request bank or payout information."/><div className="partner-profile-grid"><section className="partner-card"><h2>Organization</h2><dl className="partner-profile-list"><div><dt>Partner name</dt><dd>{selectedPartner.name}</dd></div><div><dt>Type</dt><dd>{selectedPartner.type}</dd></div><div><dt>City</dt><dd>{selectedPartner.city}</dd></div><div><dt>Referral code</dt><dd>{selectedPartner.referralCode}</dd></div><div><dt>Commission rate</dt><dd>5%</dd></div><div><dt>Verification</dt><dd>Verified — Demo</dd></div></dl></section><form className="partner-card" onSubmit={event=>{event.preventDefault();updateDemoProfile({contactDisplayName:contact,publicReferralLabel:label});setSaved(true)}}><h2>Edit Demo Profile</h2><label><span>Contact display name</span><input value={contact} onChange={event=>setContact(event.target.value)}/></label><label><span>Public referral label</span><input value={label} onChange={event=>setLabel(event.target.value)}/></label><button className="partner-primary" type="submit">Save Demo Profile</button><p className="partner-live" aria-live="polite">{saved?'Saved in this prototype session.':''}</p></form></div></>}
